//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.2914.16
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace bookSourceUI.WebReference1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    [System.Web.Services.WebServiceBindingAttribute(Name="getBooksSoap", Namespace="http://tempuri.org/")]
    public class getBooks : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public getBooks() {
            this.Url = "http://66.129.68.165/bookSource/getBooks.asmx";
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllBooks", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AllBooks() {
            object[] results = this.Invoke("AllBooks", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BeginAllBooks(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AllBooks", new object[0], callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.Data.DataSet EndAllBooks(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllBooksByCat", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AllBooksByCat(int catId) {
            object[] results = this.Invoke("AllBooksByCat", new object[] {
                        catId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BeginAllBooksByCat(int catId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AllBooksByCat", new object[] {
                        catId}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.Data.DataSet EndAllBooksByCat(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
