//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.2914.16
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace bookSourceUI.WebReference1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    [System.Web.Services.WebServiceBindingAttribute(Name="orderBooksSoap", Namespace="http://tempuri.org/")]
    public class orderBooks : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public orderBooks() {
            this.Url = "http://66.129.68.165/bookSource/orderBooks.asmx";
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/orderIem", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string orderIem(int CT_ID, string BK_ISBN, int BKOR_Quantity, System.Double BKOR_Price) {
            object[] results = this.Invoke("orderIem", new object[] {
                        CT_ID,
                        BK_ISBN,
                        BKOR_Quantity,
                        BKOR_Price});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BeginorderIem(int CT_ID, string BK_ISBN, int BKOR_Quantity, System.Double BKOR_Price, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("orderIem", new object[] {
                        CT_ID,
                        BK_ISBN,
                        BKOR_Quantity,
                        BKOR_Price}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndorderIem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
