//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.2914.16
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace bookSourceUI.WebReference1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    [System.Web.Services.WebServiceBindingAttribute(Name="sellerAdminSoap", Namespace="http://tempuri.org/")]
    public class sellerAdmin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public sellerAdmin() {
            this.Url = "http://66.129.68.165/bookSource/sellerAdmin.asmx";
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addItem", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string addItem(string ISBN, string author, System.Double price, string title, string description, string imagePath, int CAT_ID) {
            object[] results = this.Invoke("addItem", new object[] {
                        ISBN,
                        author,
                        price,
                        title,
                        description,
                        imagePath,
                        CAT_ID});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BeginaddItem(string ISBN, string author, System.Double price, string title, string description, string imagePath, int CAT_ID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addItem", new object[] {
                        ISBN,
                        author,
                        price,
                        title,
                        description,
                        imagePath,
                        CAT_ID}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndaddItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/removeItem", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string removeItem(string ISBN) {
            object[] results = this.Invoke("removeItem", new object[] {
                        ISBN});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BeginremoveItem(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("removeItem", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndremoveItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateItem", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateItem(string ISBN, string author, System.Double price, string title, string description, string imagePath, int CAT_ID) {
            object[] results = this.Invoke("updateItem", new object[] {
                        ISBN,
                        author,
                        price,
                        title,
                        description,
                        imagePath,
                        CAT_ID});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BeginupdateItem(string ISBN, string author, System.Double price, string title, string description, string imagePath, int CAT_ID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateItem", new object[] {
                        ISBN,
                        author,
                        price,
                        title,
                        description,
                        imagePath,
                        CAT_ID}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndupdateItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addCat", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string addCat(string CAT_Name) {
            object[] results = this.Invoke("addCat", new object[] {
                        CAT_Name});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BeginaddCat(string CAT_Name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addCat", new object[] {
                        CAT_Name}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndaddCat(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateCat", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateCat(int CAT_ID, string CAT_Name) {
            object[] results = this.Invoke("updateCat", new object[] {
                        CAT_ID,
                        CAT_Name});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BeginupdateCat(int CAT_ID, string CAT_Name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateCat", new object[] {
                        CAT_ID,
                        CAT_Name}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndupdateCat(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/removeCat", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string removeCat(int CAT_ID) {
            object[] results = this.Invoke("removeCat", new object[] {
                        CAT_ID});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BeginremoveCat(int CAT_ID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("removeCat", new object[] {
                        CAT_ID}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndremoveCat(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
